zuul:
  ignoredPatterns:
    - /**/admin/**
  routes:
    first:
      path: /first/**
      url: https://login.aliexpress.com/
    second:
      path: /second/**
      retryable: true
      #serviceId 和url只能取其一
      serviceId: rcms_service
    third:
      path: /third/**
      retryable: true
      serviceId: portal_service
    legacy:
      path: /**
      url: forward:/error/

services:
  rcms_service:
    ribbon:
      listOfServers: http://httpbin.org, https://httpbin.org:443
      ConnectTimeout: 50000
      ReadTimeout: 50000
      MaxAutoRetries: 1
      MaxHttpConnectionsPerHost: 200
      MaxTotalHttpConnections: 500

  portal_service:
    ribbon:
      listOfServers: http://www.baidu.com, http://www.baidu.com
      ConnectTimeout: 50000
      ReadTimeout: 50000
      MaxAutoRetries: 1
      MaxHttpConnectionsPerHost: 200
      MaxTotalHttpConnections: 500



User:
  1:
    name : icbc
    secret: xxxxx